version: '3.8'

services:
  front-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: front-dev
    restart: always
    ports:
      - 5173:5173
    volumes:
      - ./:/app/
      - ./node_modules:/app/node_modules
  front-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front-prod
    restart: on-failure:10
    ports:
      - 1824:1824
